SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_TREE AS IT
 JOIN ITEM_INFO AS II
 ON IT.ITEM_ID = II.ITEM_ID
WHERE IT.PARENT_ITEM_ID IN (SELECT ITEM_ID
                            FROM ITEM_INFO AS II
                            WHERE II.RARITY = 'RARE')
ORDER BY II.ITEM_ID DESC;