SELECT MONTH(start_date) AS MONTH, CAR_ID, COUNT(history_id) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID
                 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                 WHERE MONTH(start_date) BETWEEN 8 AND 10
                 GROUP BY CAR_ID
                 HAVING COUNT(*) >= 5)
                 AND MONTH(start_date) BETWEEN 8 AND 10
GROUP BY car_id, MONTH
HAVING RECORDS >= 1
ORDER BY MONTH ASC, CAR_ID DESC;