WITH MAX_COLONY_SIZES AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
            MAX(SIZE_OF_COLONY) AS MAX_SIZE_OF_COLONY
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT M.YEAR,
        M.MAX_SIZE_OF_COLONY - E.SIZE_OF_COLONY AS YEAR_DEV,
        E.ID
FROM ECOLI_DATA AS E
 JOIN MAX_COLONY_SIZES AS M
 ON YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY M.YEAR ASC, YEAR_DEV ASC;