SELECT DISTINCT(C.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR AS C INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
        ON C.car_id = H.car_id
WHERE C.car_type = '세단' AND H.start_date LIKE '2022-10%'
ORDER BY CAR_ID DESC;